apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx
  name: github-event-ingress
  namespace: argo-events
spec:
  rules:
    - host: engineering-az1.github-webhook.cloud.insitehq.net
      http:
        paths:
          - backend:
              service:
                name: github-eventsource-svc
                port:
                  number: 12000
            path: /
            pathType: Prefix
